### ISSUE TITLE
Uplift

### ISSUE THREAD

**Issue by ghost** [OneIdentity/IdentityManager.Dockerfiles#3]
Is there any plan to uplift the source files to suit a v9+ solution? (Specifically 9.0 LTS CU3)

Getting some attribute errors with importing the projshell (done by someone else, I'd expect them to be competent enough to follow the docx proceedure).

**Comment by MarkusWeiss-Ehlers** [comment]
All Docker build files can use command-line arguments to choose the container image version to use. It's just the default version that is still 8.2 because it doesn't matter.

If you still have a concrete issue we would need a complete repro scenario to look into this.

**Comment by ghost** [comment]
This was specifically the [CyberArk](https://github.com/OneIdentity/IdentityManager.CyberArk/) repo - README says to post issues here. We don't run containers, but need to integrate with CyberArk

**Comment by MarkusWeiss-Ehlers** [comment]
Closing this issue as it is related to a different repository https://github.com/OneIdentity/IdentityManager.CyberArk

**Comment by ghost** [comment]
README in CyberArk repository CLEARLY states to post issues here - One Identity need to sort themselves out

**Comment by MarkusWeiss-Ehlers** [comment]
The README.md in the CyberArk Solution Accelerator GitHub repository contains the wrong backing links for the issues and the project page. They point to the wrong Dockerfiles repository. 

I've updated the links. Thanks for letting us know.
